{
 "title": "NR5103 Distributions",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "band",
    "label": "4G Band",
    "query": "show tag values with key = \"INTF_Current_Band\""
   }
  ]
 },
 "panels": [
  {
   "title": "5G RSRP (dBm)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_INTF_Current_Band",
     "groupBy": [
      { "params": [ "INTF_Current_Band" ], "type": "tag" }
     ],
     "measurement": "status",
     "query": "from(bucket: \"nr5103\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"NSA_RSRP\")\n  |> filter(fn: (r) => exists r.INTF_Current_Band)\n  |> filter(fn: (r) => contains(value: r.INTF_Current_Band, set: ${band:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"INTF_Current_Band\"])\n  |> toFloat()\n  |> histogram(bins: linearBins(start: -100.0, width: 1.0, count: 16, infinity: true), normalize: true)\n  |> difference()\n  |> map(fn:(r) => ({ r with le: string(v: r.le)}))\n  |> pivot(rowKey: [\"le\"], columnKey: [\"INTF_Current_Band\"], valueColumn: \"_value\")",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "INTF_Current_Band", "operator": "=~", "value": "/^$band$/" },
      { "condition": "AND", "key": "INTF_Status", "operator": "=", "value": "Up" }
     ]
    }
   ]
  },
  {
   "title": "4G RSRP (dBm)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_INTF_Current_Band",
     "groupBy": [
      { "params": [ "INTF_Current_Band" ], "type": "tag" }
     ],
     "measurement": "status",
     "query": "from(bucket: \"nr5103\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"INTF_RSRP\")\n  |> filter(fn: (r) => exists r.INTF_Current_Band)\n  |> filter(fn: (r) => contains(value: r.INTF_Current_Band, set: ${band:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"INTF_Current_Band\"])\n  |> toFloat()\n  |> histogram(bins: linearBins(start: -95.0, width: 1.0, count: 19, infinity: true), normalize: true)\n  |> difference()\n  |> map(fn:(r) => ({ r with le: string(v: r.le)}))\n  |> pivot(rowKey: [\"le\"], columnKey: [\"INTF_Current_Band\"], valueColumn: \"_value\")",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "INTF_Current_Band", "operator": "=~", "value": "/^$band$/" },
      { "condition": "AND", "key": "INTF_Status", "operator": "=", "value": "Up" }
     ]
    }
   ]
  },
  {
   "title": "5G SINR",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_INTF_Current_Band",
     "groupBy": [
      { "params": [ "INTF_Current_Band" ], "type": "tag" }
     ],
     "measurement": "status",
     "query": "from(bucket: \"nr5103\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"NSA_SINR\")\n  |> filter(fn: (r) => exists r.INTF_Current_Band)\n  |> filter(fn: (r) => contains(value: r.INTF_Current_Band, set: ${band:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"INTF_Current_Band\"])\n  |> toFloat()\n  |> histogram(bins: linearBins(start: 0.0, width: 10.0, count: 17, infinity: true), normalize: true)\n  |> difference()\n  |> map(fn:(r) => ({ r with le: string(v: r.le) }))\n  |> pivot(rowKey: [\"le\"], columnKey: [\"INTF_Current_Band\"], valueColumn: \"_value\")",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "INTF_Current_Band", "operator": "=~", "value": "/^$band$/" },
      { "condition": "AND", "key": "INTF_Status", "operator": "=", "value": "Up" }
     ]
    }
   ]
  },
  {
   "title": "4G SINR",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_INTF_Current_Band",
     "groupBy": [
      { "params": [ "INTF_Current_Band" ], "type": "tag" }
     ],
     "measurement": "status",
     "query": "from(bucket: \"nr5103\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"INTF_SINR\")\n  |> filter(fn: (r) => exists r.INTF_Current_Band)\n  |> filter(fn: (r) => contains(value: r.INTF_Current_Band, set: ${band:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"INTF_Current_Band\"])\n  |> toFloat()\n  |> histogram(bins: linearBins(start: 9.0, width: 1.0, count: 12, infinity: true), normalize: true)\n  |> difference()\n  |> map(fn:(r) => ({ r with le: string(v: r.le) }))\n  |> pivot(rowKey: [\"le\"], columnKey: [\"INTF_Current_Band\"], valueColumn: \"_value\")",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "INTF_Current_Band", "operator": "=~", "value": "/^$band$/" },
      { "condition": "AND", "key": "INTF_Status", "operator": "=", "value": "Up" }
     ]
    }
   ]
  },
  {
   "title": "5G RSRQ (dBm)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_INTF_Current_Band",
     "groupBy": [
      { "params": [ "INTF_Current_Band" ], "type": "tag" }
     ],
     "measurement": "status",
     "query": "from(bucket: \"nr5103\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"NSA_RSRQ\")\n  |> filter(fn: (r) => exists r.INTF_Current_Band)\n  |> filter(fn: (r) => contains(value: r.INTF_Current_Band, set: ${band:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"INTF_Current_Band\"])\n  |> toFloat()\n  |> histogram(bins: linearBins(start: -17.0, width: 1.0, count: 8, infinity: true), normalize: true)\n  |> difference()\n  |> map(fn:(r) => ({ r with le: string(v: r.le)}))\n  |> pivot(rowKey: [\"le\"], columnKey: [\"INTF_Current_Band\"], valueColumn: \"_value\")",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "INTF_Current_Band", "operator": "=~", "value": "/^$band$/" },
      { "condition": "AND", "key": "INTF_Status", "operator": "=", "value": "Up" }
     ]
    }
   ]
  },
  {
   "title": "4G RSRQ (dBm)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_INTF_Current_Band",
     "groupBy": [
      { "params": [ "INTF_Current_Band" ], "type": "tag" }
     ],
     "measurement": "status",
     "query": "from(bucket: \"nr5103\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"INTF_RSRQ\")\n  |> filter(fn: (r) => exists r.INTF_Current_Band)\n  |> filter(fn: (r) => contains(value: r.INTF_Current_Band, set: ${band:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"INTF_Current_Band\"])\n  |> toFloat()\n  |> histogram(bins: linearBins(start: -18.0, width: 1.0, count: 10, infinity: true), normalize: true)\n  |> difference()\n  |> map(fn:(r) => ({ r with le: string(v: r.le)}))\n  |> pivot(rowKey: [\"le\"], columnKey: [\"INTF_Current_Band\"], valueColumn: \"_value\")",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "INTF_Current_Band", "operator": "=~", "value": "/^$band$/" },
      { "condition": "AND", "key": "INTF_Status", "operator": "=", "value": "Up" }
     ]
    }
   ]
  },
  {
   "title": "Ping (ms)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_INTF_Current_Band",
     "groupBy": [
      { "params": [ "INTF_Current_Band" ], "type": "tag" }
     ],
     "measurement": "status",
     "query": "from(bucket: \"nr5103\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ping_ms\")\n  |> filter(fn: (r) => exists r.INTF_Current_Band)\n  |> filter(fn: (r) => contains(value: r.INTF_Current_Band, set: ${band:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"INTF_Current_Band\"])\n  |> histogram(bins: linearBins(start: 20.0, width: 5.0, count: 15, infinity: true), normalize: true)\n  |> difference()\n  |> map(fn:(r) => ({ r with le: string(v: r.le)}))\n  |> pivot(rowKey: [\"le\"], columnKey: [\"INTF_Current_Band\"], valueColumn: \"_value\")",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "INTF_Current_Band", "operator": "=~", "value": "/^$band$/" },
      { "condition": "AND", "key": "INTF_Status", "operator": "=", "value": "Up" }
     ]
    }
   ]
  }
 ]
}