{
 "title": "NR5103 Status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Current Band",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"autogen\".\"status\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "5G",
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "measurement": "status",
     "query": "SELECT mean(\"INTF_RSRP\") FROM \"status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "INTF_RSRP" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSRQ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "5G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "NSA_RSRQ" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_RSRQ" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SINR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "5G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "NSA_SINR" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_SINR" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "5G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_RSRP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSRQ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "5G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "NSA_RSRQ" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_RSRQ" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SINR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "5G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "NSA_SINR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_SINR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "4G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "INTF_RSSI" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_ping_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ping_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ping_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "status",
     "query": "SELECT derivative(\"BytesReceived\") FROM \"autogen\".\"status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "BytesReceived" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "status",
     "query": "SELECT derivative(\"BytesSent\") FROM \"autogen\".\"status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "BytesSent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Received errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "status",
     "query": "SELECT derivative(\"ErrorsReceived\") FROM \"autogen\".\"status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ErrorsReceived" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Sent errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "status",
     "query": "SELECT derivative(\"ErrorsSent\") FROM \"autogen\".\"status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ErrorsSent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  }
 ]
}